services:
  build:
    container_name: dynq-build
    build:
      context: docker/build
    depends_on:
      - dynamodb
    environment:
      DYNAMODB_ENDPOINT_URL: http://dynamodb:8000
    tty: true
    stdin_open: true

  dynamodb:
    container_name: dynq-dynamodb
    image: benward2301/dynamodb-local-dvd-rental
