#!/bin/bash
set -e
working_dir=$(pwd)
project_dir=${working_dir/%\/dynq\/*/\/dynq\/}
script_dir="$(dirname "$(realpath $0)")"

docker exec -t dynq-build bash -c "mvn $@"
docker cp -q dynq-build:/dynq/target $project_dir
